"""bands table

Revision ID: b817ccd163b5
Revises: 
Create Date: 2017-12-27 12:11:51.039595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b817ccd163b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute('CREATE SCHEMA gigsvc') 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('town_city', sa.Text(), nullable=True),
    sa.Column('ffo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.Text(), nullable=True),
    sa.Column('num_members', sa.Integer(), nullable=True),
    sa.Column('dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='gigsvc'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('band', schema='gigsvc')
    # ### end Alembic commands ###
